function figurePath = visualize_text_link_overview(frame, cfg)
%VISUALIZE_TEXT_LINK_OVERVIEW Export a plain-language end-to-end overview.

resultDir = fullfile(fileparts(mfilename("fullpath")), "results", "text_link_stages");
if ~exist(resultDir, "dir")
    mkdir(resultDir);
end
figurePath = fullfile(resultDir, "00_beginner_overview.png");

colors.blue = [86, 180, 233] / 255;
colors.green = [0, 158, 115] / 255;
colors.orange = [230, 159, 0] / 255;
colors.yellow = [240, 228, 66] / 255;
colors.purple = [204, 121, 167] / 255;
colors.gray = [0.94, 0.94, 0.94];
colors.dark = [0.16, 0.16, 0.16];

fig = figure("Color", "w", "Position", [40, 60, 1600, 900], ...
    "Visible", "off");
annotation(fig, "textbox", [0.04, 0.925, 0.92, 0.06], ...
    "String", "一张图看懂：文字如何变成水声信号，再恢复成文字", ...
    "FontName", "Microsoft YaHei", "FontSize", 22, ...
    "FontWeight", "bold", "HorizontalAlignment", "center", ...
    "EdgeColor", "none");
annotation(fig, "textbox", [0.10, 0.875, 0.82, 0.04], ...
    "String", sprintf("本次示例：1 帧 | 信噪比 %.1f dB | 同步峰 %.3f | 估计频偏 %.2f Hz | 最终比特错误 %g", ...
    cfg.snrDb, frame.syncMetric, frame.frequencyOffsetHz, frame.bitErrors), ...
    "FontName", "Microsoft YaHei", "FontSize", 11, ...
    "HorizontalAlignment", "center", "EdgeColor", "none", ...
    "Color", colors.dark);

lane_label(fig, [0.015, 0.65, 0.065, 0.17], "发射端", colors.blue);
lane_label(fig, [0.015, 0.445, 0.065, 0.13], "水声信道", colors.orange);
lane_label(fig, [0.015, 0.19, 0.065, 0.17], "接收端", colors.green);

boxWidth = 0.155;
boxHeight = 0.17;
x = [0.09, 0.275, 0.46, 0.645, 0.83];
txY = 0.65;
rxY = 0.19;

payloadHex = join(compose("%02X", frame.payload), " ");
packetHex = join(compose("%02X", frame.txPacket(1:min(6, end))), " ");

stage_box(fig, [x(1), txY, boxWidth, boxHeight], "1  文字变成数字", ...
    sprintf("输入：UTF-8 文字\n载荷：%s\n输出：%d 个有效字节", ...
    payloadHex, numel(frame.payload)), colors.blue);
stage_box(fig, [x(2), txY, boxWidth, boxHeight], "2  装进固定数据包", ...
    sprintf("加入长度、序号和校验\n开头示例：%s ...\n输出：16 字节 = 128 位", ...
    packetHex), colors.blue);
stage_box(fig, [x(3), txY, boxWidth, boxHeight], "3  增加防错线索", ...
    "保留原来的 128 位\n再增加 64 个校验位\n输出：192 位", colors.blue);
stage_box(fig, [x(4), txY, boxWidth, boxHeight], "4  数字变成复数符号", ...
    "每 2 位选择 1 个点\n00、01、10、11 对应四个点\n输出：96 个 QPSK 符号", colors.blue);
stage_box(fig, [x(5), txY, boxWidth, boxHeight], "5  加标记并平滑波形", ...
    "前后加入已知 UW 标记\nRRC 平滑，减少带外能量\n输出：可发送的连续波形", colors.blue);
for index = 1:4
    horizontal_arrow(fig, x(index) + boxWidth, x(index + 1), txY + boxHeight / 2);
end

channelX = 0.09;
channelY = 0.435;
channelWidth = 0.895;
channelHeight = 0.15;
stage_box(fig, [channelX, channelY, channelWidth, channelHeight], ...
    "6  声音在水中传播", ...
    sprintf("同一信号沿 %d 条路径到达，产生回声、衰减和相位变化；再叠加 %.1f Hz 多普勒与噪声。\n路径时延：%s ms", ...
    numel(cfg.pathDelaysMs), cfg.dopplerHz(1), ...
    join(compose("%.1f", cfg.pathDelaysMs), "、")), colors.orange);
vertical_arrow(fig, x(5) + boxWidth / 2, txY, channelY + channelHeight);

stage_box(fig, [x(1), rxY, boxWidth, boxHeight], "7  把声音采成数字", ...
    sprintf("麦克风/ADC 记录波形\n采样率：%.0f kHz\n得到：%d 个采样点", ...
    cfg.rxSampleRate / 1e3, numel(frame.adcSamples)), colors.green);
stage_box(fig, [x(2), rxY, boxWidth, boxHeight], "8  找到信号从哪开始", ...
    sprintf("搜索已知 UW 标记\n同步峰 %.3f，大于门限 %.2f\n帧起点：第 %d 个采样", ...
    frame.syncMetric, cfg.syncThreshold, frame.frameStartSample), colors.green);
stage_box(fig, [x(3), rxY, boxWidth, boxHeight], "9  估计传播造成的变形", ...
    sprintf("估计频率偏移：%.2f Hz\n估计多径响应：%d 个抽头\n为后续消除回声做准备", ...
    frame.frequencyOffsetHz, cfg.channelTaps), colors.green);
stage_box(fig, [x(4), rxY, boxWidth, boxHeight], "10  消除回声并纠错", ...
    sprintf("SC-FDE 抵消多径\nLDPC 利用校验位纠错\n译码前硬错误：%d", ...
    sum(frame.txCodeBits ~= frame.demodulation.codeHardBits)), colors.green);
stage_box(fig, [x(5), rxY, boxWidth, boxHeight], "11  检查并恢复文字", ...
    sprintf("包头：%s  CRC：%s\n最终比特错误：%g\n输出：原始 UTF-8 文字", ...
    pass_text(frame.headerOk), pass_text(frame.crcOk), frame.bitErrors), colors.green);
for index = 1:4
    horizontal_arrow(fig, x(index) + boxWidth, x(index + 1), rxY + boxHeight / 2);
end
vertical_arrow(fig, x(1) + boxWidth / 2, channelY, rxY + boxHeight);

annotation(fig, "textbox", [0.08, 0.035, 0.88, 0.105], ...
    "String", ["术语翻译：  UW = 接收机认识的定位标记    " ...
    "LDPC = 给数据增加防错线索    QPSK = 用四个复数点表示二进制    " ...
    "RRC = 平滑波形、限制带宽    SC-FDE = 在频域抵消水下回声    " ...
    "CRC = 检查整包数据是否正确"], ...
    "FontName", "Microsoft YaHei", "FontSize", 11, ...
    "BackgroundColor", colors.gray, "EdgeColor", [0.7, 0.7, 0.7], ...
    "LineWidth", 1.0, "Margin", 12, "HorizontalAlignment", "left");

exportgraphics(fig, figurePath, "Resolution", 220);
exportgraphics(fig, fullfile(resultDir, "00_beginner_overview.pdf"), ...
    "ContentType", "vector");
close(fig);
end

function stage_box(fig, position, heading, body, color)
body = replace(string(body), "\n", newline);
annotation(fig, "textbox", position, "String", heading + newline + newline + body, ...
    "FontName", "Microsoft YaHei", "FontSize", 10.5, ...
    "FontWeight", "normal", "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", "BackgroundColor", 0.84 * color + 0.16, ...
    "EdgeColor", color * 0.72, "LineWidth", 1.6, "Margin", 8, ...
    "Interpreter", "none");
end

function lane_label(fig, position, textValue, color)
annotation(fig, "textbox", position, "String", textValue, ...
    "FontName", "Microsoft YaHei", "FontSize", 13, ...
    "FontWeight", "bold", "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle", "BackgroundColor", color, ...
    "Color", "w", "EdgeColor", "none");
end

function horizontal_arrow(fig, xStart, xEnd, y)
annotation(fig, "arrow", [xStart + 0.005, xEnd - 0.005], [y, y], ...
    "Color", [0.35, 0.35, 0.35], "LineWidth", 1.3, "HeadLength", 8);
end

function vertical_arrow(fig, x, yStart, yEnd)
annotation(fig, "arrow", [x, x], [yStart - 0.008, yEnd + 0.008], ...
    "Color", [0.35, 0.35, 0.35], "LineWidth", 1.5, "HeadLength", 9);
end

function textValue = pass_text(value)
if value
    textValue = "通过";
else
    textValue = "失败";
end
end
