function registry = equalizer_registry()
%EQUALIZER_REGISTRY Built-in equalizer modules for the pluggable receiver bank.
% Each entry maps an equalizer ID to a module function with the contract
%   receiver = equalizer(channel, source, cfg)
% where receiver.outputs{1} are the symbol estimates used by the metric.
%
% Chapter grouping (book "Single-Carrier Underwater Acoustic Communication"):
%   ch2  time-domain equalizers (TDE)
%   ch3  frequency-domain equalizers (FDE) and IBDFE
%   ch4  iterative/turbo equalizers (TEQ)
%   ch5  CCK receivers
%   ch6  CSK receivers
% The scenario field declares the receiver-bank scenario that runs each
% ID: qpsk (17), turbo (10), cck (7), csk (3).

ids = [ ...
    "dfe", "lms-dfe", "nlms-dfe", "rls-dfe", "dpll-dfe", ...
    "mc-lms-dfe", "mc-nlms-dfe", "mc-rls-dfe", "ptr-dfe", "subband-ptr-dfe", ...
    "mmse-fde", "zf-fde", "htfde", "sd-ibdfe", "hd-ibdfe", ...
    "ice-sd-ibdfe", "ice-hd-ibdfe", ...
    "td-turbo", "fd-dfe", "fd-turbo", "tf-turbo", "bitf-turbo", ...
    "blms-tf-turbo", "fblms", "tdda-teq", "fdda-teq", "fdda-dfe-teq", ...
    "cck-rake", "cck-dfe", "cck-bidfe", "cck-bidfe2", "cck-tr-diversity", ...
    "cck-fde", "cck-mfb", ...
    "csk-matched-filter", "csk-soft-sic", "csk-ese"];
modules = { ...
    @scfde.equalizers.conventional_dfe, ...
    @scfde.equalizers.lms_dfe, @scfde.equalizers.nlms_dfe, ...
    @scfde.equalizers.rls_dfe, @scfde.equalizers.dpll_dfe, ...
    @scfde.equalizers.mc_lms_dfe, @scfde.equalizers.mc_nlms_dfe, ...
    @scfde.equalizers.mc_rls_dfe, @scfde.equalizers.ptr_dfe, ...
    @scfde.equalizers.subband_ptr_dfe, ...
    @scfde.equalizers.mmse_fde, @scfde.equalizers.zf_fde, ...
    @scfde.equalizers.htfde, @scfde.equalizers.sd_ibdfe, ...
    @scfde.equalizers.hd_ibdfe, @scfde.equalizers.ice_sd_ibdfe, ...
    @scfde.equalizers.ice_hd_ibdfe, ...
    @scfde.equalizers.td_turbo, @scfde.equalizers.fd_dfe, ...
    @scfde.equalizers.fd_turbo, @scfde.equalizers.tf_turbo, ...
    @scfde.equalizers.bitf_turbo, @scfde.equalizers.blms_tf_turbo, ...
    @scfde.equalizers.fblms, ...
    @scfde.equalizers.tdda_teq, @scfde.equalizers.fdda_teq_true, ...
    @scfde.equalizers.fdda_dfe_teq, ...
    @scfde.equalizers.cck_rake, @scfde.equalizers.cck_dfe, ...
    @scfde.equalizers.cck_bidfe, @scfde.equalizers.cck_bidfe2, ...
    @scfde.equalizers.cck_tr_diversity, @scfde.equalizers.cck_fde, ...
    @scfde.equalizers.cck_mfb, ...
    @scfde.equalizers.csk_matched_filter, ...
    @scfde.equalizers.csk_soft_sic, @scfde.equalizers.csk_ese};
chapters = [repmat(2, 1, 10), repmat(3, 1, 7), ...
    repmat(4, 1, 10), repmat(5, 1, 7), repmat(6, 1, 3)];
scenarios = [repmat("qpsk", 1, 17), repmat("turbo", 1, 10), ...
    repmat("cck", 1, 7), repmat("csk", 1, 3)];
registry = struct("id", {ids}, "module", {modules}, ...
    "chapter", {chapters}, "scenario", {scenarios});
end
