function experiments = list_simulations()
%LIST_SIMULATIONS Display the unified simulation experiment IDs.

ids = ["paper.chapter2"; "paper.chapter3"; "paper.chapter4"; ...
    "engineering.sc_tde"; "engineering.sc_fde"; ...
    "engineering.iterative"; "engineering.cck"; "engineering.csk"; ...
    "engineering.text"];
descriptions = ["Paper UW and SC-FDE"; ...
    "Paper synchronization and Doppler"; ...
    "Paper decision-feedback equalization"; ...
    "Engineering single-carrier TDE"; "Engineering SC-FDE"; ...
    "Engineering iterative equalization"; "Engineering CCK"; ...
    "Engineering CSK and multiuser"; "Engineering text end-to-end link"];
experiments = table(ids, descriptions, ...
    'VariableNames', {'ID', 'Description'});
if nargout == 0
    disp(experiments);
end
end
