function receiver = dpll_dfe(channel, source, cfg)
%DPLL_DFE NLMS DFE with DPLL carrier-phase tracking (book (2-26)~(2-43)).
[decisions, mse, estimates, trace] = scfde.equalizers.adaptive_dfe_core( ...
    channel.received, source.tx, cfg, "nlms", true);
% (2-35)/(2-36)/(2-37): phi_k = Im{ p_k (d_k + q_k)* } with p_k the
% feedforward output and q_k = b^H d~ the positive feedback term;
% theta_{k+1} = theta_k + K1 phi_k + K2 sum phi, K2 = 0.1 K1.
trace.updateEquation = "(2-35)/(2-36)/(2-37) DPLL: phi=Im{p (d+q)*}, theta+=K1 phi+K2 sum phi, K2=0.1 K1";
trace.stepParameters = struct("K1", cfg.dpllProportionalGain, ...
    "K2", cfg.dpllIntegralGain, "K2overK1", ...
    cfg.dpllIntegralGain / cfg.dpllProportionalGain, ...
    "nlmsStepMu", cfg.nlmsStep, "delta", 1e-5, ...
    "feedforwardTaps", cfg.feedforwardTaps, ...
    "feedbackTaps", cfg.feedbackTaps);
trace.formulaStatus = "BOOK-EXACT";
trace.formulaMode = "book";
trace.bookExperimentEquivalent = false;
trace.effectiveParameters = trace.stepParameters;
receiver = scfde.equalizers.pack_equalizer("DPLL-DFE", "dpll-dfe", ...
    decisions, mse, estimates, trace);
end
